FROM nginx

LABEL maintainer="rollin.hand@gmx.de"
LABEL version="${version}"

# In maven/ the files as specified in the <assembly> section is stored
# and need to be added manually
COPY nginx.conf /etc/nginx/nginx.conf